/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewAppIdRouteImport } from './routes/review.$appId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewAppIdRoute = ReviewAppIdRouteImport.update({
  id: '/review/$appId',
  path: '/review/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/decisions': typeof DecisionsRoute
  '/evidence': typeof EvidenceRoute
  '/overview': typeof OverviewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/review/$appId': typeof ReviewAppIdRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/decisions': typeof DecisionsRoute
  '/evidence': typeof EvidenceRoute
  '/overview': typeof OverviewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/review/$appId': typeof ReviewAppIdRoute
  '/review': typeof ReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/decisions': typeof DecisionsRoute
  '/evidence': typeof EvidenceRoute
  '/overview': typeof OverviewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/review/$appId': typeof ReviewAppIdRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/apply'
    | '/assessment'
    | '/decisions'
    | '/evidence'
    | '/overview'
    | '/profile'
    | '/settings'
    | '/review/$appId'
    | '/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/apply'
    | '/assessment'
    | '/decisions'
    | '/evidence'
    | '/overview'
    | '/profile'
    | '/settings'
    | '/review/$appId'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/apply'
    | '/assessment'
    | '/decisions'
    | '/evidence'
    | '/overview'
    | '/profile'
    | '/settings'
    | '/review/$appId'
    | '/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ApplyRoute: typeof ApplyRoute
  AssessmentRoute: typeof AssessmentRoute
  DecisionsRoute: typeof DecisionsRoute
  EvidenceRoute: typeof EvidenceRoute
  OverviewRoute: typeof OverviewRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ReviewAppIdRoute: typeof ReviewAppIdRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$appId': {
      id: '/review/$appId'
      path: '/review/$appId'
      fullPath: '/review/$appId'
      preLoaderRoute: typeof ReviewAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  ApplyRoute: ApplyRoute,
  AssessmentRoute: AssessmentRoute,
  DecisionsRoute: DecisionsRoute,
  EvidenceRoute: EvidenceRoute,
  OverviewRoute: OverviewRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ReviewAppIdRoute: ReviewAppIdRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
